#pragma once

#include "NativeGameplayTags.h"

namespace RagnarokGameplayTags
{
	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Global_SetByCaller_BaseDamage);
	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Global_Event_HitReact);
	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Global_Ability_HitReact);
	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Global_Ability_Death);

	RAGNAROK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Global_State_Dead);
}